### ISSUE TITLE
关于容器中DNS解析错误问题

### ISSUE THREAD

**Issue by haideeyuan** [alauda/kube-ovn#109]
依据这个网址快速教程安装了kube-ovn
https://github.com/alauda/kube-ovn/wiki/%E5%BF%AB%E9%80%9F%E5%AE%89%E8%A3%85
一切步骤都没问题，也得到了响应的结果。节点之间，pods之间以及node和pod之间都能ping通。

但是容器内部只能通过IP访问外网，域名无法解析。请问这是什么原因那？

下图是kube-dns的内容，Endpoints看起来无异常：
![image](https://user-images.githubusercontent.com/32299609/65409252-d0320b00-de19-11e9-912a-fef8e532cb2e.png)

节点（宿主机）可以用域名访问外网，能正常解析域名。

**Comment by halfcrazy** [comment]
pod内用nslookup baidu.com 10.96.0.10 有结果返回吗？
宿主机用nslookup baidu.com 10.96.0.10 有结果返回吗？

**Comment by haideeyuan** [comment]
> pod内用 nslookup baidu.com 10.96.0.10 是否有返回
> 宿主机用 nslookup baidu.com 10.96.0.10 是否有返回
> 以及
> pod内用 nslookup kubernetes.default.svc.cluster.local 10.96.0.10 是否有返回
> 宿主机用 nslookup kubernetes.default.svc.cluster.local 10.96.0.10 是否有返回

4种情况均没有返回：
下图是容器内命令
![image](https://user-images.githubusercontent.com/32299609/65412893-bf39c780-de22-11e9-8589-2b3258efeb26.png)


下图是宿主机命令
![image](https://user-images.githubusercontent.com/32299609/65412917-cb258980-de22-11e9-9eff-f24524f32887.png)

但是dns服务器地址换成我自己的kube-dns的IP是可以在宿主机解析的如下图：
![image](https://user-images.githubusercontent.com/32299609/65413112-3c653c80-de23-11e9-81da-422c1226b0d0.png)
容器内仍然无效：
![image](https://user-images.githubusercontent.com/32299609/65413135-49822b80-de23-11e9-93b7-c149a490cc13.png)

**Comment by halfcrazy** [comment]
在容器内试下dns的pod ip，而不是svc ip。
nslookup kubernetes.default.svc.cluster.local 10.16.0.11 (dns的pod ip）

**Comment by haideeyuan** [comment]
容器中使用podIP也不可以，pod信息如下图：
![image](https://user-images.githubusercontent.com/32299609/65415529-843a9280-de28-11e9-9762-312b68f5532a.png)
容器中输入命令如下：
![image](https://user-images.githubusercontent.com/32299609/65415570-9fa59d80-de28-11e9-9bf1-742a7d23913b.png)

另外，kube-dns的dnspolicy有要求吗？我这个集群是default而不是ClusterFirst。
![image](https://user-images.githubusercontent.com/32299609/65415713-d8457700-de28-11e9-9307-5bc293bcfa43.png)

**Comment by halfcrazy** [comment]
dnspolicy应该不影响。容器内的结果和宿主机结果不一样这点很奇怪。宿主机用直接用dns的pod ip有结果吗？
另外我看你之前访问的kube-dns的svc ip是10.65.0.2，你那边是修改了默认的dns地址（10.96.0.10）吗？

Best wishes

Yan Zhu


haideeyuan <notifications@github.com> 于2019年9月23日周一 下午5:37写道：

**Comment by haideeyuan** [comment]
我后来发现我pod的dnspolicy是clusterfirst模式，我之前看的是kube-dns的svc的dnspolicy是defualt模式，这应该都是默认状态，倒是看不问题。

宿主机使用nslookup命令，不论后面的IP是podIP还是svcIP还是不写都可以找到地址了。之前不写IP确实是找不到。这期间我啥都没干就出去吃个饭，没动电脑。囧。
![image](https://user-images.githubusercontent.com/32299609/65427869-df2eb280-de45-11e9-8a9b-d9b85cb078c1.png)

但是容器（Pod）里，仍然怎样都找不到。
![image](https://user-images.githubusercontent.com/32299609/65428023-2cab1f80-de46-11e9-819e-7a59e9d9f291.png)

kube-dns服务的IP我确实安装k8s时设定为10.65.0.2了。我是在网上下载的ansible装的，里面原本就写的这个IP我就没改，这个会有影响吗？倒是可以改回去，我安装k8s的相关配置文件如下：

`# 集群部署节点：一般为运行ansible 脚本的节点
# 变量 NTP_ENABLED (=yes/no) 设置集群是否安装 chrony 时间同步
[deploy]
10.18.127.7 NTP_ENABLED=no

# etcd集群请提供如下NODE_NAME，注意etcd集群必须是1,3,5,7...奇数个节点
[etcd]
10.18.127.7 NODE_NAME=etcd1
#10.18.127.8 NODE_NAME=etcd2


[kube-master]
10.18.127.7

[kube-node]
10.18.127.7
10.18.127.8
#[new-node]
#10.2.152.131


# 参数 NEW_INSTALL：yes表示新建，no表示使用已有harbor服务器
# 如果不使用域名，可以设置 HARBOR_DOMAIN=""
[harbor]
#192.168.1.8 HARBOR_DOMAIN="harbor.yourdomain.com" NEW_INSTALL=no

# 负载均衡(目前已支持多于2节点，一般2节点就够了) 安装 haproxy+keepalived
[lb]
10.18.127.7 LB_ROLE=master

#【可选】外部负载均衡，用于自有环境负载转发 NodePort 暴露的服务等
[ex-lb]
#192.168.1.6 LB_ROLE=backup EX_VIP=192.168.1.250
#192.168.1.7 LB_ROLE=master EX_VIP=192.168.1.250

[all:vars]
# ---------集群主要参数---------------
#集群部署模式：allinone, single-master, multi-master
DEPLOY_MODE=single-master

# 集群 MASTER IP即 LB节点VIP地址，为区别与默认apiserver端口，设置VIP监听的服务端口8443
# 公有云上请使用云负载均衡内网地址和监听端口
MASTER_IP="10.18.127.7"
KUBE_APISERVER="https://{{ MASTER_IP }}:8443"

# 集群网络插件，目前支持calico, flannel, kube-router, cilium
#CLUSTER_NETWORK="calico"

# 服务网段 (Service CIDR），注意不要与内网已有网段冲突
SERVICE_CIDR="10.65.0.0/16"

# POD 网段 (Cluster CIDR），注意不要与内网已有网段冲突
CLUSTER_CIDR="172.16.0.0/16"

# 服务端口范围 (NodePort Range)
NODE_PORT_RANGE="20000-40000"

# kubernetes 服务 IP (预分配，一般是 SERVICE_CIDR 中第一个IP)
CLUSTER_KUBERNETES_SVC_IP="10.65.0.1"

### **# 集群 DNS 服务 IP (从 SERVICE_CIDR 中预分配)
CLUSTER_DNS_SVC_IP="10.65.0.2"**

# 集群 DNS 域名
CLUSTER_DNS_DOMAIN="cluster.local."

# ---------附加参数--------------------
#默认二进制文件目录
bin_dir="/opt/kube/bin"

#证书目录
ca_dir="/etc/kubernetes/ssl"

#部署目录，即 ansible 工作目录，建议不要修改
base_dir="/etc/ansible"`

**Comment by oilbeater** [comment]
我们发现 controller 在启动多个的时候可能会有冲突的情况，能不能到 ovn-central 容器里用 ovn-nbctl list load_balancer 看一下是否存在多个 udp lb

或者可以使用 0.8 的镜像更新一下已经解决了这个问题
