### ISSUE TITLE
The metric provided by pinger may not correct 

### ISSUE THREAD

**Issue by DeepLJH0001** [alauda/kube-ovn#122]
when i draw a grafana dashboard, and using `pinger_node_ping_latency_ms_bucket`  metric to build a heatmap , found the metrics may not correct.
![image](https://user-images.githubusercontent.com/18078924/67066130-b333f200-f1a3-11e9-820c-50c38eea847d.png)

average latency was below 0.5ms，but the `pinger_node_ping_latency_ms_bucket` was higher than 0.5ms

**Comment by DeepLJH0001** [comment]
the cluster has installed `prometheus operator` and the `servicemonitor` was:
```
apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    creationTimestamp: "2019-10-09T08:19:42Z"
    generation: 2
    name: kube-ovn-explorer
    namespace: kube-ovn
    resourceVersion: "4529152"
    selfLink: /apis/monitoring.coreos.com/v1/namespaces/kube-ovn/servicemonitors/kube-ovn-explorer
    uid: ef00ebda-5b4e-449e-8c9f-a005b05fb137
  spec:
    endpoints:
    - port: http
      scheme: http
    selector:
      matchLabels:
        app: kube-ovn-pinger
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by oilbeater** [comment]
@DeepLJH0001 can you inspect the log of pinger to see the actual ping latency of node? The log should show the actual ping latency every time it invoke a ping request

**Comment by DeepLJH0001** [comment]
![image](https://user-images.githubusercontent.com/18078924/67068595-268e3180-f1ad-11e9-8c20-94a0827eb83a.png)
i was exec the pinger pod and ping the node, the latency actually below the info in the log

**Comment by DeepLJH0001** [comment]
https://github.com/sparrc/go-ping/blob/master/ping.go#L92 ,the default Interval was one second, kube-ovn pinger new `goping.NewPinger` and set ping.count was 5 ,but the pinger argInterval is 5 second.
If go-ping was not thread-safe, may cause this problem. I will do a exp.

**Comment by oilbeater** [comment]
The Statistics of go-ping when running in parallel is not accurate. Now we serialize the ping and may use other implementation later
