### ISSUE TITLE
don't run privilege if possible

### ISSUE THREAD

**Issue by vsxen** [alauda/kube-ovn#128]
貌似往宿主机写文件需要特权模式？
kubelet不一定都开启了这个参数。
另外其他cni貌似都没这个要求。

另外rpm也是完全基于ovs的官方构建的？

**Comment by oilbeater** [comment]
kube-ovn 需要更改宿主机的网络（网卡，iptable，ipset 等等），这块的权限未来可以缩减。

rpm 目前是基于自己做了一些小修改，改动在策略路由的优先级上，别的地方和官方是一致的

**Comment by vsxen** [comment]
另外可以考虑共用基础镜像？ 或者all in one 然后不同的entrypoint?

**Comment by oilbeater** [comment]
@vsxen master 上已经把大部分的 privillege 去掉了，有一些需要更改 proc/sys 的 linux 下没有对应的 capability，放到了 init container 里，不会长期运行
