### ISSUE TITLE
Checking DNS resolution should use correct prefix.

### ISSUE THREAD

**Issue by sbskas** [alauda/kube-ovn#147]
For now the kube-ovn-pinger is doing a few checks to verify everything is in order.
It does some ping and verify the proper dns resolution of kubernetes.default.svc.cluster.local.
However, the local kuberntes domain is configuration dependant and can be changed.
If the cluster is configured with something different from the default cluster.local, dns check fails.

IMHO, the kubernetes local domain should be infered from the apiserver or in an easier way, the kube-ovn-pinger should check kubernetes.default rather than the FQDN kubernetes.default.<local domain>.

**Comment by oilbeater** [comment]
That's right, we should use kubernetes.default to check the dns resolution. Can you make a pr to fix it? @sbskas

**Comment by sbskas** [comment]
Opened #149
