### ISSUE TITLE
Relation bewteen kube-ovn CIDR and kubernetes CIDR

### ISSUE THREAD

**Issue by sbskas** [alauda/kube-ovn#148]
While testing kube-ovn, I couldn't figure out wether the podNetwork and serviceNetwork should be related to the default cidr or if one should drop the  following flags from the controller-manager :
```
--allocate-node-cidrs=true
--cluster-cidr=x.x.0.0/16
--node-cidr-mask-size=24
```
and let the kube-ovn controller do the job.

**Comment by oilbeater** [comment]
kube-ovn will take over pod ip allocation so these flag is not needed and you can use subnet to define which cidr you want to use at anytime. The service ip is still allocated by kube-controller-manager if you want to change the service network cidr you still need to set the controller-manager flag

**Comment by sbskas** [comment]
Thanks for the reply. Do you think it's relevant to mention it in the documentation or not ?

**Comment by oilbeater** [comment]
Yeah, I will add a doc to it
