### ISSUE TITLE
有更新文档么

### ISSUE THREAD

**Issue by aland-zhang** [alauda/kube-ovn#217]
找了半天没发现有更新文档 比如 怎么从 v0.8.0 升级到 v0.10.1 版本呢？升级流程是什么，怎么才能尽可能的不中断服务升级？

**Comment by oilbeater** [comment]
0.8 到 0.10 之间镜像和 yaml 都发生了比较多的变化，而且期间经历了 ovs 的升级，cluster 模式高可用的方式发生了变化，不建议用原地升级的方式。

如果是采用非高可用部署方式，可以采用先停止 kube-ovn-controller 和 kube-ovn-cni ，更新 ovn 相关组件再更新 kube-ovn-controller 和 kube-ovn-cni 的方式升级，建议提前进行测试

**Comment by aland-zhang** [comment]
好的，在没有稳定下来还不能在生产环境中使用是吧。那预计哪个版本可以在生产环境中使用呢？

**Comment by oilbeater** [comment]
最近两个版本主要是稳定性和监控相关的修复，我们希望尽可能发现隐藏的稳定性相关问题，如果没有其他已知问题的话，预计春节后将会发长期支持版本。功能和使用方式上和 0.10 比暂时不会发生变化，也欢迎试用现在的版本，帮我们看一下还有什么问题 ：）
