### ISSUE TITLE
cni error when testing for a pod failure 

### ISSUE THREAD

**Issue by laik** [alauda/kube-ovn#218]
kuberneter v1.17.0
centos-7 kernel : 5.2.8-1.el7.elrepo.x86_64
kube-ovn version v0.10.0
1月 06 02:16:20 node2 kubelet[3756]: E0106 02:16:20.865784    3756 cni.go:364] Error adding dxp_water-injector-sample-2-a-w-01-5f9cfb847f-h7lfx/9be8e8b5e39e9e68363f2780b52253823c0d116e326d677bae6778d816803d96 to network kube-ovn/kube-ovn: request ip return 500 no available ip for pod dxp/water-injector-sample-2-a-w-01-5f9cfb847f-h7lfx

**Comment by oilbeater** [comment]
It seems like that kube-ovn-controller didn't allocate ip to this pod. Can you paste the log of kube-ovn-controller?

**Comment by laik** [comment]
I collected the controller logs

`I0108 03:29:12.957430       1 ovn-nbctl.go:22] ovn-nbctl command --timeout=30 --may-exist lb-add cluster-udp-loadbalancer 10.96.0.10:53 10.16.0.23:53,10.16.0.6:53 udp in 3ms
E0108 03:29:12.959206       1 endpoint.go:140] failed to update vip 10.96.0.10:53 to udp lb, 2020-01-08T03:29:12Z|00001|unixctl|WARN|failed to connect to /var/run/openvswitch/ovn-nbctl.7.ctl
ovn-nbctl: /var/run/openvswitch/ovn-nbctl.7.ctl: could not connect to ovn-nb daemon (Protocol error); unset OVN_NB_DAEMON to avoid using daemon
, exit status 1
E0108 03:29:12.959246       1 endpoint.go:83] error syncing 'kube-system/kube-dns': 2020-01-08T03:29:12Z|00001|unixctl|WARN|failed to connect to /var/run/openvswitch/ovn-nbctl.7.ctl
ovn-nbctl: /var/run/openvswitch/ovn-nbctl.7.ctl: could not connect to ovn-nb daemon (Protocol error); unset OVN_NB_DAEMON to avoid using daemon
, exit status 1, requeuing
I0108 03:29:12.960865       1 ovn-nbctl.go:22] ovn-nbctl command --timeout=30 --may-exist lb-add cluster-tcp-loadbalancer 10.96.62.70:8080 10.16.0.10:8080,10.16.0.12:8080,10.16.0.2:8080,10.16.0.7:8080,10.16.0.8:8080 tcp in 3ms
E0108 03:29:12.960884       1 endpoint.go:126] failed to update vip 10.96.62.70:8080 to tcp lb, 2020-01-08T03:29:12Z|00001|unixctl|WARN|failed to connect to /var/run/openvswitch/ovn-nbctl.7.ctl
ovn-nbctl: /var/run/openvswitch/ovn-nbctl.7.ctl: could not connect to ovn-nb daemon (Protocol error); unset OVN_NB_DAEMON to avoid using daemon
, exit status 1
E0108 03:29:12.960900       1 endpoint.go:83] error syncing 'kube-ovn/kube-ovn-pinger': 2020-01-08T03:29:12Z|00001|unixctl|WARN|failed to connect to /var/run/openvswitch/ovn-nbctl.7.ctl
ovn-nbctl: /var/run/openvswitch/ovn-nbctl.7.ctl: could not connect to ovn-nb daemon (Protocol error); unset OVN_NB_DAEMON to avoid using daemon
, exit status 1, requeuing
I0108 03:29:12.964074       1 ovn-nbctl.go:22] ovn-nbctl command --timeout=30 --may-exist lb-add cluster-tcp-loadbalancer 10.96.11.212:9093 10.16.0.11:9093,10.16.0.28:9093,10.16.0.5:9093 tcp in 6ms
E0108 03:29:12.964094       1 endpoint.go:126] failed to update vip 10.96.11.212:9093 to tcp lb, 2020-01-08T03:29:12Z|00001|unixctl|WARN|failed to connect to /var/run/openvswitch/ovn-nbctl.7.ctl
ovn-nbctl: /var/run/openvswitch/ovn-nbctl.7.ctl: could not connect to ovn-nb daemon (Protocol error); unset OVN_NB_DAEMON to avoid using daemon
, exit status 1
E0108 03:29:12.964111       1 endpoint.go:83] error syncing 'monitoring/alertmanager-main': 2020-01-08T03:29:12Z|00001|unixctl|WARN|failed to connect to /var/run/openvswitch/ovn-nbctl.7.ctl
ovn-nbctl: /var/run/openvswitch/ovn-nbctl.7.ctl: could not connect to ovn-nb daemon (Protocol error); unset OVN_NB_DAEMON to avoid using daemon
, exit status 1, requeuing
I0108 03:29:16.953267       1 pod.go:679] update pod kube-ovn/kube-ovn-pinger-5rh88
I0108 03:29:16.957445       1 ovn-nbctl.go:22] ovn-nbctl command --timeout=30 get logical_switch_port kube-ovn-pinger-5rh88.kube-ovn addresses in 4ms
E0108 03:29:16.957469       1 ovn-nbctl.go:393] get port kube-ovn-pinger-5rh88.kube-ovn addresses failed 2020-01-08T03:29:16Z|00001|unixctl|WARN|failed to connect to /var/run/openvswitch/ovn-nbctl.7.ctl
ovn-nbctl: /var/run/openvswitch/ovn-nbctl.7.ctl: could not connect to ovn-nb daemon (Protocol error); unset OVN_NB_DAEMON to avoid using daemon
, exit status 1
E0108 03:29:16.957495       1 pod.go:392] error syncing 'kube-ovn/kube-ovn-pinger-5rh88': 2020-01-08T03:29:16Z|00001|unixctl|WARN|failed to connect to /var/run/openvswitch/ovn-nbctl.7.ctl
ovn-nbctl: /var/run/openvswitch/ovn-nbctl.7.ctl: could not connect to ovn-nb daemon (Protocol error); unset OVN_NB_DAEMON to avoid using daemon
, exit status 1, requeuing
I0108 03:30:51.382916       1 endpoint.go:95] update endpoint kubernetes-dashboard/kubernetes-dashboard
I0108 03:30:51.389187       1 ovn-nbctl.go:22] ovn-nbctl command --timeout=30 --may-exist lb-add cluster-tcp-loadbalancer 10.96.86.3:443 10.16.0.25:8443 tcp in 6ms
E0108 03:30:51.389234       1 endpoint.go:126] failed to update vip 10.96.86.3:443 to tcp lb, 2020-01-08T03:30:51Z|00001|unixctl|WARN|failed to connect to /var/run/openvswitch/ovn-nbctl.7.ctl
ovn-nbctl: /var/run/openvswitch/ovn-nbctl.7.ctl: could not connect to ovn-nb daemon (Protocol error); unset OVN_NB_DAEMON to avoid using daemon
, exit status 1
E0108 03:30:51.389281       1 endpoint.go:83] error syncing 'kubernetes-dashboard/kubernetes-dashboard': 2020-01-08T03:30:51Z|00001|unixctl|WARN|failed to connect to /var/run/openvswitch/ovn-nbctl.7.ctl
ovn-nbctl: /var/run/openvswitch/ovn-nbctl.7.ctl: could not connect to ovn-nb daemon (Protocol error); unset OVN_NB_DAEMON to avoid using daemon
, exit status 1, requeuing
I0108 03:31:11.584459       1 pod.go:679] update pod dxp/sample-0
I0108 03:31:11.588535       1 ovn-nbctl.go:22] ovn-nbctl command --timeout=30 get logical_switch_port sample-0.dxp addresses in 4ms
E0108 03:31:11.588578       1 ovn-nbctl.go:393] get port sample-0.dxp addresses failed 2020-01-08T03:31:11Z|00001|unixctl|WARN|failed to connect to /var/run/openvswitch/ovn-nbctl.7.ctl
ovn-nbctl: /var/run/openvswitch/ovn-nbctl.7.ctl: could not connect to ovn-nb daemon (Protocol error); unset OVN_NB_DAEMON to avoid using daemon
, exit status 1
E0108 03:31:11.588622       1 pod.go:392] error syncing 'dxp/sample-0': 2020-01-08T03:31:11Z|00001|unixctl|WARN|failed to connect to /var/run/openvswitch/ovn-nbctl.7.ctl
ovn-nbctl: /var/run/openvswitch/ovn-nbctl.7.ctl: could not connect to ovn-nb daemon (Protocol error); unset OVN_NB_DAEMON to avoid using daemon`

**Comment by laik** [comment]
pod  describe
`  Normal   SandboxChanged          18m (x125412 over 39h)    kubelet, node2  Pod sandbox changed, it will be killed and re-created.
  Warning  FailedCreatePodSandBox  3m50s (x125917 over 39h)  kubelet, node2  (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "52ffb35b343b88eb33ddb8a7641e662906eaf0c22df9d3994f4b349a121233b2" network for pod "sample-0": networkPlugin cni failed to set up pod "sample-0_dxp" network: request ip return 500 no available ip for pod dxp/sample-0`

**Comment by oilbeater** [comment]
The ovn-nb daemon didn't response and kube-ovn-controller can not connect to ovn-nb to update network. Can you restart the kube-ovn-controller and check if it can recovery

**Comment by laik** [comment]
an attempt was made to shut down a node's network card during a high availability test. In this case, the controller will cause the above error. close the controller pod and reschedule it.

**Comment by oilbeater** [comment]
If nbctl-daemon hangs, kube-ovn-controller can not process further network changes. https://github.com/alauda/kube-ovn/pull/216 this pr has fixed the issue by periodically check the daemon and restart when the daemon hangs

**Comment by laik** [comment]
Yes, I just found this problem "kube-ovn-cni" pod CrashLoopBackOff, just recreate it manually

**Comment by laik** [comment]
thks
