### ISSUE TITLE
Prepare for 1.0 GA

### ISSUE THREAD

**Issue by oilbeater** [alauda/kube-ovn#235]
- [x] Independent website
- [ ] Documents for GA
- [x] Gather user stories

**Comment by z5614036** [comment]
能给暴露podip给外部的操作指南就好。  macvlan网络比这个高级吗？

**Comment by oilbeater** [comment]
> 能给暴露podip给外部的操作指南就好。 macvlan网络比这个高级吗？

可以参考这个文档
https://github.com/alauda/kube-ovn/wiki/Pod-IP-%E7%9B%B4%E6%8E%A5%E5%AF%B9%E5%A4%96%E6%9A%B4%E9%9C%B2
