### ISSUE TITLE
kube-ovn怎么结合multus-cni来用？有没有个指导？

### ISSUE THREAD

**Issue by AlawnWong** [alauda/kube-ovn#238]
kube-ovn怎么结合multus-cni来用？有没有个指导？

**Comment by oilbeater** [comment]
正常来说把 kube-ovn 在 /etc/cni/net.d 下的配置写到 multus-cni delegate 的部分即可。问一下是想使用哪两个网络插件，碰到了什么问题

**Comment by AlawnWong** [comment]
@oilbeater  
我想使用multus-cni，calico作为主网络网络插件，kube-ovn作为副网络插件，自己试了试，没有配通。
只看到 #199 有部分提及。 
想请教有没有指导。

**Comment by oilbeater** [comment]
现在还没有这方面的文档，能否发一下配置和具体的问题，我们试验一下来完善这块

**Comment by AlawnWong** [comment]
1. multus-cni +calico 使用kubespray安装。
参照 https://github.com/kubernetes-sigs/kubespray/blob/a9b67d586b80b3de9afbf38908f194d0a1df6d5d/docs/multus.md 这个安装的。
2. kube-ovn 参照 https://github.com/alauda/kube-ovn/wiki/%E5%BF%AB%E9%80%9F%E5%AE%89%E8%A3%85 来的。
3. 安装完 kube-ovn之后，就不知道/etc/cni/net.d/ 下的配置如何设置了。。。

**Comment by AlawnWong** [comment]
@oilbeater  你们还有什么建议吗？

**Comment by Ranler** [comment]
已测试kube-ovn可以作为multus的主网络

**Comment by gitnote-images** [comment]
@Ranler 抽空分享一下呗

**Comment by Ranler** [comment]
> 
> 
> @Ranler 抽空分享一下呗

把kube-ovn的cni配置加到multus的delegates列表中即可，作为第一个主网络(eth0)没有问题，但是不能作为副网络。

**Comment by oilbeater** [comment]
https://github.com/alauda/kube-ovn/wiki/%E5%A4%9A%E7%BD%91%E5%8D%A1%E6%94%AF%E6%8C%81
