### ISSUE TITLE
请教一下ovn 逻辑接口的流量统计是如何做的.

### ISSUE THREAD

**Issue by zhuoqiang08** [alauda/kube-ovn#27]
首先感谢你的代码，想取到逻辑交换机/路由器 上的端口流量，来实现的端口的流量统计功能。这个有实现的办法吗？

**Comment by oilbeater** [comment]
可以再每个节点用用ovs-vsctl 命令获取端口的 statistics

`ovs-vsctl get interface <iface-id> statistics`
