### ISSUE TITLE
Question: Can you give some detail on the hairpin LB w/ OVN?

### ISSUE THREAD

**Issue by yongming** [alauda/kube-ovn#311]
In the release note of kube-ovn 1.1, you claimed new feature of hairpin LB, can you provide an introduction on it? Thanks.

**Comment by oilbeater** [comment]
It's a  new feature in OVN 20.03. Before this version, pod can not access itself from a svc that point to itself.  The path of `Pod-A -> SVC-A -> Pod-A` doesn't work. From OVN 20.03 this hairpin path can work.

**Comment by yongming** [comment]
Get it, thanks.
