### ISSUE TITLE
kubectl plugin fail

### ISSUE THREAD

**Issue by watchworld** [alauda/kube-ovn#312]
kubectl plugin list 
display
plugin in /usr/local/bin/kubectl-ko
but when I run "kubectl ko "，display "no such file or directory"

**Comment by oilbeater** [comment]
Which version of kubectl do you use? Does kubectl-ko has executable permission?

**Comment by watchworld** [comment]
kubectl version is 1.18 
kubectl-ko (chmod +x)

**Comment by oilbeater** [comment]
Run /usr/local/bin/kubectl-ko directly, to check if it works

**Comment by watchworld** [comment]
it note works，error info:/bin/bash^M: bad interpreter: No such file or directory

**Comment by watchworld** [comment]
the reason I find that is kubectl-ko file format dos，I use dos2unix command that is ok.
