### ISSUE TITLE
Cloud I set traffic rate limits for a subnet

### ISSUE THREAD

**Issue by Icedroid** [alauda/kube-ovn#373]
Qos can only set pod Ingress/Egress traffic rate limits, Cloud It set traffic rate limits for k8s service or a subnet base on a namespace ?

**Comment by oilbeater** [comment]
For now, the answer is no. The subnet in Kube-OVN will be distributed in all nodes. That means if rate limits is to be implemented,  there must be some mechanism to count up traffic rate on all nodes in realtime and adjust QoS on all nodes, that is not possible now. As the service is also implemented in a distributed way, there are same problems in implementing service rate limit.

One possible way to implement subnet rate limits is to limit the central gateway traffic for a subnet. That means only traffic from/to outside the cluster will be limited. Is that what you want?

**Comment by Icedroid** [comment]
@oilbeater Yeah. Only want to limit traffic from/to outside the cluster, how to do/deploy the central gateway traffic for a subnet?

**Comment by oilbeater** [comment]
@Icedroid https://github.com/alauda/kube-ovn/blob/master/docs/subnet.md#gateway
