### ISSUE TITLE
Update CustomResourceDefinition to v1

### ISSUE THREAD

**Issue by floryut** [alauda/kube-ovn#379]
`The apiextensions.k8s.io/v1beta1 version of CustomResourceDefinition is deprecated and will no longer be served in v1.19.`

With Kubernetes version 1.19 coming soon, kube-ovn crd should be updated to `apiextensions.k8s.io/v1`.

Ref file: kube-ovn/yamls/crd.yaml

**Comment by oilbeater** [comment]
@floryut Thanks! We wil fix it.
