### ISSUE TITLE
Deployment optimize in hybrid-architecture cluster

### ISSUE THREAD

**Issue by Pastens** [alauda/kube-ovn#407]
**Issue Brief:** 
Currently kube-ovn deployment in hybrid-architecture cluster (x86_64 and arm64 node in same cluster) is difficult due to different image name of different architecture. In my practice, it requires a node-selector in deployment yaml to distinguish the different architecture, which has a lot changes in your deployment scripts and yamls.

**Recommendation:**
Like the other official images(e.g. https://hub.docker.com/_/nginx?tab=tags), please merge different arch images to one same tag. 
You can achieve this feature by a simple "docker manifest" command in this page section "The hard way with docker manifest
" https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/ .

It'll help us a lot if kube-ovn official images do so. Thanks.

**Comment by Pastens** [comment]
To be more specific, currently we need to modify the VERSION to "v1.2.1-arm" for arm64 or "v1.2.1" for x86_64 in your install.sh script. But failed to deploy in hybrid-architecture cluster without deep modification (e.g. add node-selectors) in the scripts or yamls.

**Comment by oilbeater** [comment]
@Pastens Thanks for the recommendation, we will look into this

**Comment by Pastens** [comment]
> @Pastens Thanks for the recommendation, we will look into this

I am now working on it in my fork repo. Any progress will be updated here and let you know. @oilbeater

**Comment by Pastens** [comment]
> > @Pastens Thanks for the recommendation, we will look into this
> 
> I am now working on it in my fork repo. Any progress will be updated here and let you know. @oilbeater

@oilbeater 
Hi, here is the result of my attempt to build multi-arch images. As the link below, the same tag (both commit-tag or version-tag) contains both amd64 and arm64 version, so that our current cluster(mainly amd64 arch) could scale up to some arm64 server nodes without change the kube-ovn deployment yaml.

But there is still some problems remain. I'll fix and fully test it before an official PR (may modify some of your build scripts).

Ref: https://hub.docker.com/r/pastens/kube-ovn/tags

**Comment by oilbeater** [comment]
resolved in https://github.com/alauda/kube-ovn/pull/616
