### ISSUE TITLE
我们对openshift做过适配吗？

### ISSUE THREAD

**Issue by XueCangQiuYe** [alauda/kube-ovn#409]
现在我们的集群是使用的openshift，网络插件也是openshift-sdn

目前想做的就是将集群的管理网和计算网分离，并且pod的计算网ip是固定的。

所以选用了multus作为多网络的插件，打算选用ovn作为计算网并且固定pod的ip。

但是我看了一下相关的issue，说ovn只能作为主网络。所以我偷个懒想直接问一下：
1.ovn支持openshift吗？
2.使用multus，将openshift-sdn作为主网络，ovn作为副网络，可以吗？

感谢~！

**Comment by oilbeater** [comment]
1. 如果是标准的 openshift，没有装其他网络插件直接使用 kube-ovn 是支持的
2. openshift-sdn 使用的也是 ovs 做 datapath，猜测会和 kube-ovn 有冲突问题

**Comment by XueCangQiuYe** [comment]
@oilbeater 感谢回复。我试一下~
