### ISSUE TITLE
Problems with Qos control for centrailized gateway subnet

### ISSUE THREAD

**Issue by belegent** [alauda/kube-ovn#412]
Hi, I tried to control the cluster traffic by setting the qos of the centralized gateway node using the latest image with pre-build kube-ovn-daemon binaries. But it seems not to work for me. I have entered the cni container to confirm that the relative ingress/egress policy and qos settings have been written in ovs database. Is the function of qos control for centralized gateway subnet available now for the latest kube-ovn image? Could you update a document guiding this? Thanks.

**Comment by oilbeater** [comment]
@belegent Some OS might not set the txqlen of the nic.

Can you try `ip link set ovn0 txqueuelen 1000`, to check if the QoS can work.
