### ISSUE TITLE
Update ovs and dpdk for security reason 

### ISSUE THREAD

**Issue by oilbeater** [alauda/kube-ovn#428]
See: https://github.com/openvswitch/ovs/blob/37606fb5ca76aef478a51d407aaa06caf7fb9376/NEWS#L4

DPDK 19.11.2 and OVS 2.13 branch fix bunches of CVEs.

@garyloug Should we update the DPDK version and use 2.13 branch to build the OVS-DPDK image?

**Comment by garyloug** [comment]
Hi @oilbeater sure, I can take this task next week.

**Comment by oilbeater** [comment]
Hi @garyloug 
Thanks for the investigation. I found that dpdk-devel 19.11.2 is available in CentOS 8-stream AppStream here
https://rpmfind.net/linux/RPM/centos/8-stream/appstream/x86_64/Packages/dpdk-devel-19.11.2-1.el8.x86_64.html

However, when I changed to the stream and tried to install dpdk-devel, the perl dependency is broken. It seems to be a centos upstream repository bug https://bugzilla.redhat.com/show_bug.cgi?id=1869358

I think we can change to centos base image first, and then try the 19.11.2 dpdk-devel later, when the upstream bug is fixed

**Comment by garyloug** [comment]
Hi @oilbeater 
Thanks, I had tried 19.11.2 RPMs but the dependency chain is huge. I wasn't aware of the AppStream, I'll check it out now.
Ok, will PR the CentOS base image shortly.
