### ISSUE TITLE
两个ovn集群间的通讯是怎么配置的

### ISSUE THREAD

**Issue by aland-zhang** [alauda/kube-ovn#441]
现在我部署了两个测试k8s集群，里面都部署了独立的ovn 网络， 那么如果想让这两个集群直接相互访问对方的pod ip 怎么配置呢？谢谢。

**Comment by oilbeater** [comment]
可以使用 ovn-ic 做网络之间的互通，我们会在最近将多集群网络功能集成进来，可以关注一下

**Comment by aland-zhang** [comment]
非常感谢回复，期待这个功能早日实现。

**Comment by oilbeater** [comment]
@aland-zhang 可以参考这个文档使用多集群的功能 https://github.com/alauda/kube-ovn/blob/master/docs/cluster-interconnection.md

**Comment by aland-zhang** [comment]
这个非常好，为你们的付出点赞
