### ISSUE TITLE
Pod ovn-pinger cannot ping the k8s cluster or other pod

### ISSUE THREAD

**Issue by abigibonam** [alauda/kube-ovn#443]
我组了个1master 3worker的K8s集群，apply kube-ovn后，只能ping通在此主机上的pinger pod，无法ping通其他主机上的pod，在kube-ovn的脚本中发现ping node部分已出现ping loss count的情况，已检查route、subnet、sb和nb等，未发现问题。

**Nodes**
NAME    STATUS   ROLES    AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                   KERNEL-VERSION                CONTAINER-RUNTIME
node1   Ready    master   11h   v1.18.5   128.5.49.50    <none>        CentOS Linux 7 (AltArch)   4.14.0-115.el7a.0.1.aarch64   docker://18.9.8
node2   Ready    <none>   11h   v1.18.5   128.5.49.40    <none>        CentOS Linux 7 (AltArch)   4.14.0-115.el7a.0.1.aarch64   docker://18.9.8
node3   Ready    <none>   11h   v1.18.5   128.5.49.30    <none>        CentOS Linux 7 (AltArch)   4.14.0-115.el7a.0.1.aarch64   docker://18.9.8
node4   Ready    <none>   11h   v1.18.5   128.5.65.186   <none>        CentOS Linux 7 (AltArch)   4.14.0-115.el7a.0.1.aarch64   docker://18.9.8

**Pod**
NAMESPACE     NAME                                   READY   STATUS    RESTARTS   AGE   IP             NODE    NOMINATED NODE   READINESS GATES
kube-system   coredns-66bff467f8-92kw7               1/1     Running   0          11h   10.16.0.6      node4   <none>           <none>
kube-system   coredns-66bff467f8-w8cnd               1/1     Running   0          11h   10.16.0.8      node2   <none>           <none>
kube-system   etcd-node1                             1/1     Running   0          11h   128.5.49.50    node1   <none>           <none>
kube-system   kube-apiserver-node1                   1/1     Running   0          11h   128.5.49.50    node1   <none>           <none>
kube-system   kube-controller-manager-node1          1/1     Running   0          11h   128.5.49.50    node1   <none>           <none>
kube-system   kube-ovn-cni-6blqb                     1/1     Running   0          11h   128.5.49.40    node2   <none>           <none>
kube-system   kube-ovn-cni-fnhb8                     1/1     Running   0          11h   128.5.49.50    node1   <none>           <none>
kube-system   kube-ovn-cni-nhdqd                     1/1     Running   0          11h   128.5.49.30    node3   <none>           <none>
kube-system   kube-ovn-cni-q9cg2                     1/1     Running   0          11h   128.5.65.186   node4   <none>           <none>
kube-system   kube-ovn-controller-5646ccff47-v722d   1/1     Running   0          11h   128.5.65.186   node4   <none>           <none>
kube-system   kube-ovn-pinger-5xb7c                  1/1     Running   0          11h   10.16.0.12     node3   <none>           <none>
kube-system   kube-ovn-pinger-72rm7                  1/1     Running   0          11h   10.16.0.9      node2   <none>           <none>
kube-system   kube-ovn-pinger-bvdbk                  1/1     Running   0          11h   10.16.0.10     node1   <none>           <none>
kube-system   kube-ovn-pinger-zm4w9                  1/1     Running   0          11h   10.16.0.11     node4   <none>           <none>
kube-system   kube-proxy-7h2qs                       1/1     Running   0          11h   128.5.49.50    node1   <none>           <none>
kube-system   kube-proxy-b6fvb                       1/1     Running   0          11h   128.5.65.186   node4   <none>           <none>
kube-system   kube-proxy-mk96g                       1/1     Running   0          11h   128.5.49.30    node3   <none>           <none>
kube-system   kube-proxy-txqc6                       1/1     Running   0          11h   128.5.49.40    node2   <none>           <none>
kube-system   kube-scheduler-node1                   1/1     Running   0          11h   128.5.49.50    node1   <none>           <none>
kube-system   ovn-central-744b69cf89-kjdph           1/1     Running   0          11h   128.5.49.50    node1   <none>           <none>
kube-system   ovs-ovn-5l4x7                          1/1     Running   0          11h   128.5.49.40    node2   <none>           <none>
kube-system   ovs-ovn-nsvwl                          1/1     Running   0          11h   128.5.65.186   node4   <none>           <none>
kube-system   ovs-ovn-tt78r                          1/1     Running   0          11h   128.5.49.50    node1   <none>           <none>
kube-system   ovs-ovn-zr9kv                          1/1     Running   0          11h   128.5.49.30    node3   <none>           <none>

**Pinger LOG**
I0818 01:49:59.357840   97493 ping.go:112] ping pod: kube-ovn-pinger-5xb7c 10.16.0.12, count: 3, loss count 0, average rtt 15.01ms
I0818 01:50:00.358645   97493 ping.go:112] ping pod: kube-ovn-pinger-72rm7 10.16.0.9, count: 3, loss count 3, average rtt 0.00ms
I0818 01:50:01.359383   97493 ping.go:112] ping pod: kube-ovn-pinger-bvdbk 10.16.0.10, count: 3, loss count 3, average rtt 0.00ms
I0818 01:50:02.360241   97493 ping.go:112] ping pod: kube-ovn-pinger-zm4w9 10.16.0.11, count: 3, loss count 3, average rtt 0.00ms
I0818 01:50:02.360266   97493 ping.go:157] start to check dns connectivity
E0818 01:50:12.360642   97493 ping.go:165] failed to resolve dns kubernetes.default, lookup kubernetes.default on 10.96.0.10:53: dial udp 10.96.0.10:53: i/o timeout
I0818 01:50:12.360690   97493 ping.go:174] start to check dns connectivity
E0818 01:50:22.361119   97493 ping.go:182] failed to resolve dns alauda.cn, lookup alauda.cn on 10.96.0.10:53: dial udp 10.96.0.10:53: i/o timeout
I0818 01:50:22.361166   97493 ping.go:132] start to check ping external to 114.114.114.114
I0818 01:50:22.481130   97493 ping.go:145] ping external address: 114.114.114.114, total count: 3, loss count 0, average rtt 18.03ms

**Subnet**
NAME          PROTOCOL   CIDR            PRIVATE   NAT     DEFAULT   GATEWAYTYPE   USED   AVAILABLE
join          IPv4       100.64.0.0/16   false     false   false     distributed   4      65529
ovn-default   IPv4       10.16.0.0/16    false     true    true      distributed   6      65527

**Route**
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.1.1     0.0.0.0         UG    103    0        0 enp189s0f1
10.16.0.0       100.64.0.1      255.255.0.0     UG    0      0        0 ovn0
100.64.0.0      0.0.0.0         255.255.0.0     U     0      0        0 ovn0
128.5.0.0       0.0.0.0         255.255.0.0     U     101    0        0 enp189s0f0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
192.168.1.0     0.0.0.0         255.255.255.0   U     103    0        0 enp189s0f1

**Comment by oilbeater** [comment]
感觉是节点之间的隧道没有建立通信。
可以到每台机器的 ovs-ovn 容器里用 `ovs-vsctl show` 看一下 geneve 端口是否正确建立，以及 udp 的 6081 是否被防火墙放行

**Comment by abigibonam** [comment]
**ovs-vsctl**
afb133b4-9686-4d49-9f92-b832e542a504
    Bridge br-int
        ······
        Port ovn-77e349-0
            Interface ovn-77e349-0
                type: geneve
                options: {csum="true", key=flow, remote_ip="128.5.49.50"}
        Port ovn0
            Interface ovn0
                type: internal
    ovs_version: "2.13.0"

**netstat**
udp        0      0 0.0.0.0:6081            0.0.0.0:*                           -
udp6       0      0 :::6081                 :::*                                -

firewalld已关闭，看着br的interface也没问题

请问下是否有其他排查方法？看了几个log，未没看到明显的error，这个问题重装OS后依然在，感觉问题是否可能在k8s集群问题？

**Comment by oilbeater** [comment]
可以 `kubectl ko sbctl show` 看一下是否所有的node都已经注册了进去，再往后就得抓 geneve 隧道 IP 所在的端口看数据包是否正常出去了。

**Comment by yangquanli** [comment]
我有一样的问题， 用kubectl ko sbctl show 看 ，所有node 都已经注册了进去。在 node  ping pod ip 时，node 节点上ovn0 根本没收到包；反过来 ping，ovn0有收到包。就是说，ovn0 与 node ip 之间 单向通。

**Comment by oilbeater** [comment]
> 我有一样的问题， 用kubectl ko sbctl show 看 ，所有node 都已经注册了进去。在 node ping pod ip 时，node 节点上ovn0 根本没收到包；反过来 ping，ovn0有收到包。就是说，ovn0 与 node ip 之间 单向通。

在 node 上 `ip route` 看一下是否存在目的为 pod 网段的路由，这个落是否指向了 ovn0

**Comment by yangquanli** [comment]
![image](https://user-images.githubusercontent.com/18607522/91516984-6a021200-e91f-11ea-8c94-3c3a57f3f388.png)
10.99 子网就是 pod 的，

**Comment by oilbeater** [comment]
从路由规则上看应该是可以走到 ovn0 网卡的，需要看下 iptables 里是否有阻断的规则

**Comment by yangquanli** [comment]
[root@mysql1 ~]# iptables  -L  -n
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            match-set ovn40subnets dst
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            match-set ovn40subnets src
ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:6081
KUBE-SERVICES  all  --  0.0.0.0/0            0.0.0.0/0            ctstate NEW /* kubernetes service portals */
KUBE-EXTERNAL-SERVICES  all  --  0.0.0.0/0            0.0.0.0/0            ctstate NEW /* kubernetes externally-visible service portals */
KUBE-FIREWALL  all  --  0.0.0.0/0            0.0.0.0/0

Chain FORWARD (policy DROP)
target     prot opt source               destination
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            match-set ovn40subnets dst
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            match-set ovn40subnets src
KUBE-FORWARD  all  --  0.0.0.0/0            0.0.0.0/0            /* kubernetes forwarding rules */
KUBE-SERVICES  all  --  0.0.0.0/0            0.0.0.0/0            ctstate NEW /* kubernetes service portals */
DOCKER-USER  all  --  0.0.0.0/0            0.0.0.0/0
DOCKER-ISOLATION-STAGE-1  all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
DOCKER     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
KUBE-SERVICES  all  --  0.0.0.0/0            0.0.0.0/0            ctstate NEW /* kubernetes service portals */
KUBE-FIREWALL  all  --  0.0.0.0/0            0.0.0.0/0

Chain DOCKER (1 references)
target     prot opt source               destination

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
target     prot opt source               destination
DOCKER-ISOLATION-STAGE-2  all  --  0.0.0.0/0            0.0.0.0/0
RETURN     all  --  0.0.0.0/0            0.0.0.0/0

Chain DOCKER-ISOLATION-STAGE-2 (1 references)
target     prot opt source               destination
DROP       all  --  0.0.0.0/0            0.0.0.0/0
RETURN     all  --  0.0.0.0/0            0.0.0.0/0

Chain DOCKER-USER (1 references)
target     prot opt source               destination
RETURN     all  --  0.0.0.0/0            0.0.0.0/0

Chain KUBE-EXTERNAL-SERVICES (1 references)
target     prot opt source               destination

Chain KUBE-FIREWALL (2 references)
target     prot opt source               destination
DROP       all  --  0.0.0.0/0            0.0.0.0/0            /* kubernetes firewall for dropping marked packets */ mark match 0x8000/0x8000
DROP       all  -- !127.0.0.0/8          127.0.0.0/8          /* block incoming localnet connections */ ! ctstate RELATED,ESTABLISHED,DNAT

Chain KUBE-FORWARD (1 references)
target     prot opt source               destination
DROP       all  --  0.0.0.0/0            0.0.0.0/0            ctstate INVALID
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            /* kubernetes forwarding rules */ mark match 0x4000/0x4000
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            /* kubernetes forwarding conntrack pod source rule */ ctstate RELATED,ESTABLISHED
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0            /* kubernetes forwarding conntrack pod destination rule */ ctstate RELATED,ESTABLISHED

Chain KUBE-KUBELET-CANARY (0 references)
target     prot opt source               destination

Chain KUBE-PROXY-CANARY (0 references)
target     prot opt source               destination

Chain KUBE-SERVICES (3 references)
target     prot opt source               destination

**Comment by yangquanli** [comment]
iptables 规则 如上。然后执行 iptables -t filter -A FORWARD -j ACCEPT 后， 本地node ip 仍然ping 不同 pod ip

**Comment by oilbeater** [comment]
可以用 `iptables -L -nv` 看下那个规则上有丢包
