### ISSUE TITLE
Static ip for pod.

### ISSUE THREAD

**Issue by xieydd** [alauda/kube-ovn#46]
I  notice the pod ip is declared in `ovn.kubernetes.io/ip_address` or `ovn.kubernetes.io/ip_address`. Is there a graceful way to give a suggestion of ip or ips depend on cidr to avoid conflict.😝

**Comment by oilbeater** [comment]
kube-ovn now only check if a static ip is in the subnet cidr and will NOT check the conflict. From long run, maybe it's better to add an admission controller hook to check the uniqueness of ip address and prevent the conflict address to be written to the pod annotation

**Comment by xieydd** [comment]
THS, i focus on suggestion not conflict, example:
```
$ ovn get ip
10.16.0.11
$ ovn get ips -n 3
10.16.0.11
10.16.0.12
10.16.0.13
```

**Comment by oilbeater** [comment]
It can be done by a cmdline util that first fetch all allocated addresses from pod annotation and then find the available ips. However you need to make sure the allocation doesn't change in the meanwhile. I think finally we should combine the suggestion not conflict and conflict check method together

**Comment by xieydd** [comment]
Yep,Race situation need conflict check meanwhile.

**Comment by halfcrazy** [comment]
With the recently added kube-ovn-webhook #63, you can avoid conflict on Create/Update.

**Comment by oilbeater** [comment]
Now you can use `kubectl get ip` to get the allocation summary and can avoid to use the duplicated ip
