### ISSUE TITLE
Can we use kube-ovn network for k8s hosted openstack?

### ISSUE THREAD

**Issue by robinbraemer** [alauda/kube-ovn#496]
Can kube-ovn be used to provide the network overlay to an openstack installation?

For example if we run all openstack services in k8s including nova hypervisors scheduled to specific k8s nodes, could those VMs participate in kube-ovn's OVN? Surely we also want to have all networking resources to work in openstack (public floating IPs, subnets, routers, ...) [without getting garbage collected](https://github.com/alauda/kube-ovn/blob/cc8ce5ebcc685ac3a7d6ae96110597cdea2787c2/pkg/controller/gc.go)  by the kube-ovn controller.

Is this possible or is it something that should not be done with kube-ovn or are there any limitations to openstack one should know of when doing this?

Great project!

**Comment by oilbeater** [comment]
@robinbraemer I'm not experienced in openstack. In my opinion, if you want to run openstack on k8s and using the native openstack network concept, it's better to use the native neutron method and use OVN as a backend. 

One of my concerns is that kube-ovn now is trying to map some openstack network concept into k8s and there are some function gaps(vpc,dns,dhcp,lbaas), different use pattern (eg. security group vs networkpolicy) and will cause misunderstanding if try mapping openstack network concept back into kube-ovn.

One possible solution might be both kube-ovn and openstack reuse the same underlay OVN DB and use external_ids to distinguish each other to avoid the garbage collector wrongly remove objects

**Comment by robinbraemer** [comment]
> One possible solution might be both kube-ovn and openstack reuse the same underlay OVN DB and use external_ids to distinguish each other to avoid the garbage collector wrongly remove objects

Thanks, that would be great! I'm not in experienced ovn. Could you please explain how kube-ovn uses `external_ids` and how they provide isolation from openstack and kube-ovn?

**Comment by oilbeater** [comment]
> Could you please explain how kube-ovn uses external_ids and how to isolate openstack from kube-ovn?
Every object in OVN has an `external_ids` field and can be used to set user define metadata, kube-ovn can use these metadata to filter only kube-ovn owned objects to do the management work.

> I assume openstack network concepts (vpc, dns, dhcp, lbaas, ...) will just work when openstack services (neutron/octavia/...) use kube-ovn's managed ovn directly. Is that right?

I think it should work
