### ISSUE TITLE
nodeport的支持

### ISSUE THREAD

**Issue by wangwj** [alauda/kube-ovn#51]
按照文档安装后，发现nodeport类型好像是不起作用，按照我们的文档说，应该是可以的，是需要特殊配置，还是目前不支持

**Comment by oilbeater** [comment]
nodeport 需要 iptables 规则的支持，目前还需要 kube-proxy 的支持，目前同时装 kube-proxy 和 kube-ovn 是可以正常工作的。

可以贴一下你的具体试验过程，来看一下可能的问题
