### ISSUE TITLE
wiki中文教程中以下几个地方可能是错别字

### ISSUE THREAD

**Issue by anyushun** [alauda/kube-ovn#525]
- [多网卡支持](https://github.com/alauda/kube-ovn/wiki/%E5%A4%9A%E7%BD%91%E5%8D%A1%E6%94%AF%E6%8C%81) 我们已经**能过**通过 Subnet 和 IP 的 CRD 来进行 IP 的高级管理
- [Pod-固定-IP-和-Mac](https://github.com/alauda/kube-ovn/wiki/Pod-%E5%9B%BA%E5%AE%9A-IP-%E5%92%8C-Mac) 在使用 annotation 定义 Pod IP/Mac 时需要注意**一下**几点
- [Workload-固定-IP](https://github.com/alauda/kube-ovn/wiki/Workload-%E5%9B%BA%E5%AE%9A-IP) 对 Workload 使用固定 IP 需要注意**一下**几点

**Comment by oilbeater** [comment]
@anyushun 已经修改，十分感谢
