### ISSUE TITLE
Does Different Subnet share a geneve VNI?

### ISSUE THREAD

**Issue by xhzhf** [alauda/kube-ovn#527]
I am not sure different subnet have a exclusive a geneve VNI.
or kube-ovn use geneve to encapsulate packet between node just like calico use IPinIP and geneve VDI is not related to subnet.

It looks that kube-ovn obey k8s network strategy that isolation happen at IP layer not L2 layer.

**Comment by oilbeater** [comment]
As one subnet will be mapped to one logical switch in OVN concept, different subnet will have different VNI. Each subnet itself is a L2 domain, different subnet can contain same l2 address

**Comment by xhzhf** [comment]
Thanks
