### ISSUE TITLE
nodeSwitch没有loadBalancer

### ISSUE THREAD

**Issue by makoto126** [alauda/kube-ovn#53]
代码里特别注明了DO NOT add ovn dns/lb to node switch
这样从node不就无法访问service了吗？
ovn-central有两个南北桥数据库的service，kube-ovn-controller是需要访问这个service的
而kube-ovn-controller的网络类型又是hostNetwork，这样在没有kube-proxy的iptables的情况下是无法访问南北桥数据库的
请问下为什么不给node switch加上loadBalancer呢

**Comment by oilbeater** [comment]
hostnetwork 的 service 访问目前还是依赖于 kube-proxy 的 iptable. 我们之前给 node-switch 加过 lb 的规则发现有一些流量在从 node-switch 出集群时发生问题，当时怀疑是 ovn 生成的流表优先级有问题就暂时去掉了。

另外当 ovn-controller 第一次启动的时候 ovn 数据库内也是没有 lb 规则的，controller 也就无法通过 ovn 的 lb 来访问 ovn-db，所以现在还是要依赖 kube-proxy 的一些功能。不过 ovn-controller 启动后，容器内的 service 访问就都是通过 ovn lb 了，kube-proxy 的 iptable 承担的流量就很小了

**Comment by makoto126** [comment]
我看到ovn还可以把loadbalancer应用在logical router上，那么是否可以统一把Service ip都写到ovn-cluster router上呢？我不太熟悉ovn，请教一下。

**Comment by oilbeater** [comment]
是可以的，但是 router 上的 lb 会有一些限制，必须是 gateway router 才能应用 lb 规则。

并且从长远看 kube-ovn 希望做多租户的支持，每个子网会对应到一个租户，可能会出现 service ip 在不同租户间重复的情况，这种情况下将 lb 放在 logical switch ，不同 ls 应用不同的 lb 规则未来扩展性会更好一些

**Comment by oilbeater** [comment]
@makoto126 后续有问题可以再开 issue 讨论
