### ISSUE TITLE
ipset 'ovn40local-pod-ip-nat' has no members when the hostname of the k8s is different from the hostname of the host

### ISSUE THREAD

**Issue by Andywugh** [alauda/kube-ovn#60]
![image](https://user-images.githubusercontent.com/13342437/61026956-778ccd80-a3e7-11e9-987c-d64d0abb950f.png)

In pkg/daemon/gateway.go, the host name of the host is the same as the host name of the k8s cluster, and the relevant ipset collection is delivered.

**Comment by oilbeater** [comment]
@halfcrazy we should use the env `KUBE_NODE_NAME` to replace the `os.Hostname()`
