### ISSUE TITLE
Error from server (NotFound): daemonsets.apps "kube-proxy" not found

### ISSUE THREAD

**Issue by yanwei2019** [alauda/kube-ovn#654]
In our k8s，the components of k8s are deployed by binary，not pod.

So when check the kube-proxy treated as the daemonset will make an error and the subsequent process will be interrupted。

**Comment by halfcrazy** [comment]
Ok, what's the form of coredns? The diagnose script will also check the deploy coredns.

**Comment by yanwei2019** [comment]
The coredns is a deployment.
