### ISSUE TITLE
New Feature: The parameter of cni-bin-dir is configurable

### ISSUE THREAD

**Issue by yanwei2019** [alauda/kube-ovn#655]
In our K8S，the cni-bin-dir is /opt/kube/bin，not the default value /opt/cni/bin.
/opt/kube/bin/kubelet --config=/var/lib/kubelet/config.yaml --cni-bin-dir=/opt/kube/bin --cni-conf-dir=/etc/cni/net.d

**Comment by halfcrazy** [comment]
It's reasonable. We will support this case.
