### ISSUE TITLE
Edit to DPDK doc

### ISSUE THREAD

**Issue by garyloug** [alauda/kube-ovn#686]
Hi all,

I'm wondering if this edit to docs/dpdk.md was intentional?
https://github.com/alauda/kube-ovn/commit/b8f221bf7d47b2190acfd716878e1b5aa441a409#diff-0dd42c4f0585638dd336135eb7c2ecf595ecf5c29d2ad811ec421b01238ed48c

Removing the generateName results in the error:
The Pod "" is invalid: metadata.name: Required value: name or generateName is required

**Comment by oilbeater** [comment]
Some users report Pod creation failed with generateName, so I removed the generateName but forget to add the name
